version: '2'
services:
  testjhipster-app:
    image: testjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testjhipster-postgresql:5432/testJHipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://testjhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://testjhipster-elasticsearch:9200
    ports:
      - 8080:8080
  testjhipster-postgresql:
    extends:
      file: postgresql.yml
      service: testjhipster-postgresql
  testjhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: testjhipster-elasticsearch
